name: Caching for fun and profit

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/cache@v2
          env:
            cache-name: cache
          with:
            path: ~/.cache
            key: ${{ runner.os }}-build-${{ env.cache-name }}
        - run: |
            mkdir ~/.cache
            touch ~/.cache/stamp
            echo "I was generated on `date`" >> ~/.cache/stamp
            cat ~/.cache
