name: thing

on: push
jobs:
  build:
    strategy:
      matrix:
        exit-status:
        - 0
        - 1
        fail-ok:
        - false
        - true
    runs-on: ubuntu-latest
    steps:
    - run: "echo ${{matrix.exit-status}}"
      continue-on-error: ${{matrix.fail-ok}}
