name: Cache busting

on:
    workflow_dispatch:
        inputs:
            cache-key:
                description: "cache key"
                required: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/cache@v2
          with:
            path: ~/.cache
            key: ${{ runner.os }}-build-${{ github.events.inputs.cache-key }}
            restore-keys: |
                impossible-restore-key-75a0e5e2-390e-4483-bf8c-1775349969f4
        - run: |
            if ! test -d ~/.cache ; then mkdir ~/.cache; fi
            touch ~/.cache/stamp
            echo "I was manually generated on `date`" >> ~/.cache/stamp
            cat ~/.cache/stamp

